Replace MF_NATS_URL with MF_BROKER_URL (#118)
mainflux/devops pull request #120
Opened 2022-07-29 07:50 UTC by chen-dq

* issus: https://github.com/mainflux/devops/issues/118

Signed-off-by: chen.dq <chen.dq@neusoft.com>

2022-08-17 10:05 UTC, manuio requested changes
LGTM

2022-08-17 10:06 UTC, manuio approved these changes

2022-08-17 13:44 UTC, 0x6f736f646f commented on charts/mainflux/templates/adapter_coap-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
change it to a single variable i.e 

```
- name: MF_NATS_URL
  value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.messageBrokerUrl }}
```

2022-08-17 13:44 UTC, 0x6f736f646f commented on charts/mainflux/templates/adapter_http-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, manuio commented on charts/mainflux/templates/adapter_coap-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
You probably mean
```
- name: MF_BROKER_URL
  value: {{ .Values.defaults.messageBrokerUrl }}
 ```

2022-08-17 13:46 UTC, 0x6f736f646f requested changes
Also Rename `natsPort: 4222` to `messageBrokerUrl` with the correct value

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/adapter_lora-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/adapter_mqtt-statefulstet.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/adapter_opcua-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/influxdbwriter-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/mongodbwriter-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/notifier_smtp-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:46 UTC, 0x6f736f646f commented on charts/mainflux/templates/twins-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Same to here

2022-08-17 13:47 UTC, 0x6f736f646f commented on charts/mainflux/templates/adapter_coap-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
Yes

2022-08-18 06:37 UTC, chen-dq commented
> natsPort: 4222

2022-08-19 11:34 UTC, 0x6f736f646f commented
@manuio Should we make the `messageBrokerUrl` be configurable to nats, rabbitmq and possibly kafka or just use nats as the default broker

2022-08-19 11:44 UTC, manuio commented
> @manuio Should we make the `messageBrokerUrl` be configurable to nats, rabbitmq and possibly kafka or just use nats as the default broker

@0x6f736f646f I'd say that we should make it configurable and remove any hardcoded value from the charts. Not sure what to do with the `{{ .Release.Name }}`. Maybe we can have something like `{{Values.defaults.msgBrokerProtocol}}://{{ .Release.Name }}-{{msgBrokerUrl}}:{{ .Values.defaults.msgBrokerPort }}`. But it's a bit confusing and unreadable compared to `{{messageBrokerUrl}}`.

2023-06-14 05:28 UTC, arvindh123 commented on charts/mainflux/templates/adapter_coap-deployment.yaml
>                value: nats://{{ .Release.Name }}-nats-client:{{ .Values.defaults.natsPort }}
@chen-dq , 
The nats broker in the values.yaml file is referred to as `nats`, which means that the hostname of the nats broker will be {{ .Release.Name}}-nats. Can you please update this change in all the relevant locations?

```suggestion
            - name: MF_BROKER_URL
              value: nats://{{ .Release.Name }}-nats:{{ .Values.defaults.natsPort }}   
```

2023-06-14 05:33 UTC, arvindh123 commented
I also agree with @manuio  point about not changing this until we have support for all brokers.

2023-06-14 06:26 UTC, arvindh123 approved these changes
LGTM

2023-06-19 09:55 UTC, dborovcanin approved these changes

2023-06-19 09:55 UTC, merged