NOISSUE - Add mTLS over HTTP adapter
mainflux/devops pull request #55
Opened 2020-08-15 06:06 UTC by blokovi

2020-09-08 14:06 UTC, manuio commented on charts/mainflux/templates/ingress.yaml
> +{{- if and (ne .Values.nginx_internal.mtls.tls "") (ne .Values.nginx_internal.mtls.intermediate_crt "") }}
Should we use `nginxInternal` and `intermediateCrt`?

2020-09-08 14:23 UTC, blokovi commented on charts/mainflux/templates/ingress.yaml
> +{{- if and (ne .Values.nginx_internal.mtls.tls "") (ne .Values.nginx_internal.mtls.intermediate_crt "") }}
yes, thanks. camelCase is recommended naming convention
https://helm.sh/docs/chart_best_practices/values/

2020-09-09 14:05 UTC, drasko commented
Can we push this please?

2020-09-10 07:18 UTC, blokovi commented
This add mTLS termination on ingress, because ingress pass client certificate to upstream (nginx internal) where `CN` from that certificate is compared with Authorization header.
Although this works for HTTP messaging, it breaks ui (and probably other services) that don't need client certificate.
I will temporarily put this in the draft.

2020-09-10 17:41 UTC, blokovi commented
> This add mTLS termination on ingress, because ingress pass client certificate to upstream (nginx internal) where `CN` from that certificate is compared with Authorization header.
> Although this works for HTTP messaging, it breaks ui (and probably other services) that don't need client certificate.
> I will temporarily put this PR in draft.

Openning again PR, this problem is resolved with making `auth-tls-verify-client` optional on ingress

2020-09-10 17:52 UTC, manuio commented on charts/mainflux/values.yaml
> +    # hostname: "mainflux.ga"
Just curious, why `.ga` ?

2020-09-10 17:54 UTC, manuio requested changes

2020-09-10 17:54 UTC, manuio commented on charts/mainflux/templates/nginx-internal.yaml
>      - port: 8883
Should we make this configurable?

2020-09-11 06:39 UTC, blokovi commented on charts/mainflux/values.yaml
> +    # hostname: "mainflux.ga"
That's my test domain :)
Removed, thanks

2020-09-11 08:44 UTC, blokovi commented on charts/mainflux/templates/nginx-internal.yaml
>      - port: 8883
This is port for internal nginx. 
Let me try to explain how the flow for mqtts goes:
host:8883(ingress) -> nginx-internal:8883 -> envoy:1883 -> mqtt_proxy:1884 -> mqtt_broker:1883
This last two ports are already configurable, but for nginx-internal (and envoy) I think it doesn't make sense to be configurable because it's internal traffic and would be too much configuration.

2020-09-11 08:56 UTC, dusanb94 approved these changes

2020-09-11 09:05 UTC, manuio approved these changes
LGTM

2020-09-11 09:05 UTC, merged