MF-3 - Make service ports configurable
mainflux/devops pull request #57
Opened 2020-09-09 11:33 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2020-09-09 12:00 UTC, nmarcetic commented on charts/mainflux/templates/adapter_mqtt-deployment.yaml
> +            - name: MF_MQTT_ADAPTER_mqttPort
Use the upper case.

2020-09-09 12:00 UTC, nmarcetic commented on charts/mainflux/templates/adapter_mqtt-deployment.yaml
> +            - name: MF_MQTT_ADAPTER_mqttPort
Dunno, why you are changing this at all? The same is done in docker-compose, its consistent and more eye-catchy if its WS or MQTT.

2020-09-09 12:02 UTC, manuio commented on charts/mainflux/templates/adapter_mqtt-deployment.yaml
> +            - name: MF_MQTT_ADAPTER_mqttPort
Find/Replace :) Fixing this now, thank you!

2020-09-09 14:08 UTC, drasko requested changes

2020-09-09 14:08 UTC, drasko commented on charts/mainflux/README.md
> +adapter# Mainflux Helm Chart
Is this a comment or a title? Looks strange...

2020-09-09 14:32 UTC, manuio commented on charts/mainflux/README.md
> +adapter# Mainflux Helm Chart
Typo

2020-09-09 14:34 UTC, drasko approved these changes
LGTM

2020-09-09 16:03 UTC, dusanb94 submitted a review, later dismissed

2020-09-10 14:07 UTC, blokovi approved these changes

2020-09-10 14:24 UTC, drasko approved these changes
LGTM

2020-09-10 14:24 UTC, merged