NOISSUE - Fix coap adapter deployment
mainflux/devops pull request #59
Opened 2020-10-14 20:14 UTC by blokovi

Fix coap adapter deployment

Signed-off-by: Ivan Milošević <iva@blokovi.com>

2020-10-14 20:27 UTC, drasko approved these changes
LGTM

2020-10-14 20:29 UTC, drasko requested changes

2020-10-14 20:29 UTC, drasko commented on charts/mainflux/templates/ingress.yaml
> +  # CoAP adapter:
Do we need this `:` at the end of the comment. Also - is this the best place for this comment, as somehow section for the rpotocol egins abov the line `apiVersion` if I understand well...

2020-10-14 20:56 UTC, blokovi commented on charts/mainflux/templates/ingress.yaml
> +  # CoAP adapter:
I think we don't need this comment at all. Removed.

2020-10-14 21:07 UTC, drasko approved these changes
LGTM

2020-10-19 09:25 UTC, manuio approved these changes
LGTM

2020-10-19 09:25 UTC, merged