MF-64 - Fix db user role for postgresql-users
mainflux/devops pull request #65
Opened 2020-11-02 11:22 UTC by blokovi

Change postgresql-users user to postgres
Add new envars

Signed-off-by: Ivan Milosevic <iva@blokovi.com>

2020-11-02 11:23 UTC, drasko requested changes

2020-11-02 11:23 UTC, drasko commented on charts/mainflux/templates/users-deployment.yaml
> +            - name: MF_USERS_ADMIN_EMAIL
Admin of what? Some general admin, or only PotgreSQL admin?

2020-11-02 11:30 UTC, blokovi commented on charts/mainflux/templates/users-deployment.yaml
> +            - name: MF_USERS_ADMIN_EMAIL
No database. It's Mainflux default user, created on startup

https://github.com/mainflux/mainflux/blob/master/users/README.md

2020-11-06 10:59 UTC, drasko commented on charts/mainflux/templates/users-deployment.yaml
> +            - name: MF_USERS_ADMIN_EMAIL
OK, I see. Thanks.

2020-11-06 10:59 UTC, drasko approved these changes
LGTM

2020-11-06 10:59 UTC, merged