MF-72 - Update dependencies
mainflux/devops pull request #75
Opened 2021-01-22 10:43 UTC by blokovi

Update dependencies
Use superuser for postgres
Chart version bump

Resolves #72 

Signed-off-by: Ivan Milosevic <iva@blokovi.com>

2021-01-22 10:57 UTC, nmarcetic requested changes

2021-01-22 10:57 UTC, nmarcetic commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
Does it make sense to keep stable repo just because of nats? It's also available on bitnami repository. I tested with version `6.0.0` works like a charm.

2021-01-22 10:57 UTC, nmarcetic commented on charts/mainflux/Chart.yaml
> +version: 0.1.7
Which version is this? The chart is not published, it's not aligned with the release version either. Do we increment the version with each PR or how its works?

2021-01-22 10:57 UTC, nmarcetic commented on charts/mainflux/Chart.lock
>    version: 11.3.1
There is a version 12.x.x available on bitnami repo, any special reason not to update?

2021-01-22 10:57 UTC, nmarcetic commented on charts/mainflux/README.md
> +  helm repo add stable https://charts.helm.sh/stable
If you switch nats to use bitnami you can drop this.

2021-01-22 10:58 UTC, blokovi commented on charts/mainflux/Chart.lock
>    version: 11.3.1
no reason, I will test it and update

2021-01-22 11:16 UTC, blokovi commented on charts/mainflux/Chart.yaml
> +version: 0.1.7
Actually, we don't have rule for this. I just wanted to increment because this changes will not work with only `helm upgrade` if you already have installed mainflux. Because there is dependecnies changes and also postgres user is diffrent.

New chart realease should be released when mainflux core is released and then we will change default images' tags that is used in charts (now it's `0.11.0`). 
Changing postgres user (to use superuser `postgres`) in this PR is preparation for this change, because things service (and user service before) demands using superuser for creating extensions

2021-01-22 11:16 UTC, blokovi commented on charts/mainflux/Chart.yaml
> +version: 0.1.7
Actually, we don't have rule for this. I just wanted to increment because this changes will not work with only `helm upgrade` if you already have installed mainflux. Because there is dependecnies changes and also postgres user is diffrent.

New chart realease should be released when mainflux core is released and then we will change default images' tags that is used in charts (now it's `0.11.0`). 
Changing postgres user (to use superuser `postgres`) in this PR is preparation for this change, because things service (and user service before) demands using superuser for creating extensions

2021-01-22 11:21 UTC, nmarcetic commented on charts/mainflux/Chart.yaml
> +version: 0.1.7
I see , got it for ` helm upgrade`. it also makes sense to release it with the core.
Thanks for the detailed answer @blokovi

2021-01-22 11:23 UTC, nmarcetic commented on charts/mainflux/Chart.lock
>    version: 11.3.1
I tested with version `12.1.3` didn't notice any problems. But it's better if you can test it also, just to confirm.

2021-01-22 11:23 UTC, blokovi commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
Only reason I left NATS on @stable is because I tested it with latest chart version `6.1.1` and I got warnings:
```coalesce.go:199: warning: destination for tls is a table. Ignoring non-table value false```
It is just warning, but I didn't want to switch. I will test it with `6.0.0` and update if there is no warning

2021-01-22 16:39 UTC, blokovi commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
I found out what cause this warning.
In values.yaml when I have uncommented:
```
ingress:
   tls:
     hostname: "example.com"
     secret: "mainflux-server"
  ```
it's somehow conflicting with nats dependency [values](https://github.com/bitnami/charts/blob/master/bitnami/nats/values.yaml#L429):
  ```
  ingress:
    tls: false
 ```
 I tested it, it works expected, but this warning is here.

2021-01-22 18:27 UTC, blokovi commented on charts/mainflux/Chart.lock
>    version: 11.3.1
updated redis to latest version in bitnami repo

2021-01-22 18:33 UTC, blokovi commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
I can't find out why this conflict shows up, maybe it's a helm bug.
It doesn't affect on deployment, but warning is there every time when `ingress.tls` part is uncommented in `values.yaml` with nats from `bitnami` repo.
I upgraded nats to the latest version that is in `stable` repo until this issue is finally resolved.

2021-01-22 18:34 UTC, blokovi commented on charts/mainflux/README.md
> +  helm repo add stable https://charts.helm.sh/stable
Left stable for NATS, because of warning issue I explained above.

2021-01-22 19:09 UTC, manuio approved these changes
LGTM

2021-01-25 13:30 UTC, nmarcetic commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
@blokovi For the sake of testing, can you pls try to set an empty map, instead of a comment block? 
Like this ingress: {} when you want to disable. So `tls` is never null. It's a helm problem, yes, but should be resolved from version `3.2` I have helm version `3.4.2` didn't notice this warning.

2021-01-25 17:02 UTC, blokovi commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
My helm client is even newer, it's `3.5.0`
Same warning is whether I have in values.yaml:
```
ingress:
  tls: {}
```
or with configuration above:
```
ingress:
   tls:
     hostname: "example.com"
     secret: "mainflux-server"
 ```

2021-01-25 17:03 UTC, nmarcetic commented on charts/mainflux/Chart.lock
> +  repository: https://charts.helm.sh/stable
Ok, let's keep it as is until we figure out the helm issue :) Thanks for testing.

2021-01-25 17:03 UTC, nmarcetic approved these changes

2021-01-25 17:04 UTC, merged