NOISSUE - Add certs service and deployment charts
mainflux/devops pull request #78
Opened 2021-02-22 13:17 UTC by darkodraskovic

2021-02-22 13:29 UTC, mteodor commented on charts/mainflux/values.yaml
> +  hostname: "ashvin01.mainflux.io"
remove this addres

2021-02-22 13:29 UTC, mteodor commented on charts/mainflux/values.yaml
> +      tag: "latest"
latest or 0.11.0?

2021-02-22 14:24 UTC, blokovi requested changes
Add `postgresql-certs` in dependencies in Chart.yaml with `condition: certs.enabled`

2021-02-23 09:18 UTC, nmarcetic requested changes

2021-02-23 09:18 UTC, nmarcetic commented on charts/mainflux/values.yaml
> +  enabled: true
Disabled by default.

2021-02-23 09:19 UTC, nmarcetic approved these changes

2021-02-23 09:20 UTC, blokovi approved these changes

2021-02-23 09:21 UTC, merged