MF-88 - expose TCP port in coap adapter
mainflux/devops pull request #89
Opened 2021-09-13 07:33 UTC by blokovi

Signed-off-by: Ivan Milosevic <iva@blokovi.com>

Resolves #88

2022-01-10 19:29 UTC, manuio submitted a review, later dismissed
LGTM

2022-01-19 05:51 UTC, manuio submitted a review, later dismissed
LGTM

2022-01-19 12:04 UTC, dusanb94 submitted a review, later dismissed

2022-01-19 13:29 UTC, dusanb94 approved these changes

2022-01-19 13:29 UTC, manuio approved these changes

2022-01-19 13:30 UTC, merged

2022-01-19 14:00 UTC, drasko requested changes

2022-01-19 14:00 UTC, drasko commented on charts/mainflux/templates/adapter_coap-service.yaml
> +      name: "tcp-{{ .Values.adapter_coap.udpPort }}"
How come that we append something called `udpPort` to a `tcp-` prefix? Looks confising.

2022-01-19 14:09 UTC, blokovi commented on charts/mainflux/templates/adapter_coap-service.yaml
> +      name: "tcp-{{ .Values.adapter_coap.udpPort }}"
It's two different ports, items in the list of ports starts with `-`

2022-01-19 14:25 UTC, drasko commented on charts/mainflux/templates/adapter_coap-service.yaml
> +      name: "tcp-{{ .Values.adapter_coap.udpPort }}"
Why is then variable is called `udpPort`?

2022-01-19 15:04 UTC, blokovi commented on charts/mainflux/templates/adapter_coap-service.yaml
> +      name: "tcp-{{ .Values.adapter_coap.udpPort }}"
Here is PR:
https://github.com/mainflux/devops/pull/99